### ISSUE TITLE
The README is not helpful enough

### ISSUE THREAD

**Issue by heigvdgachetje** [PDG-2023/Project#21]
Could you *please* populate the README so that people can know what your President Directeur Général 2023 is about ? Thanks!

**Comment by noahboegli** [comment]
Hi @heigvdgachetje 

Thanks for your interest in this project.

Could you please explain your question in different terms, as our README does not contain any reference to `Président Directeur Général 2023`.

Looking forward to hear from you ! 

Kind Regards

Noah,
Chief Coffee Officer
