### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by nigelmann** [PDG-2023/Project#24]
- Use JWT
- Clarify is renewal will be implemented or not

**Comment by HugoMendes98** [comment]
@nigelmann @noahboegli, How do I get the connected user given the current API specifications description?

I looked in some `dev/back` branches, but found nothing. Did I miss something?

If nothing is defined yet, I propose to return the user or its id when calling the _validate_ endpoint.

**Comment by noahboegli** [comment]
@HugoMendes98  Can we close this ?

**Comment by nigelmann** [comment]
Authencation has been enforced on merge
- https://github.com/PDG-2023/Project/pull/52

Let me know if everything is ok for you @HugoMendes98 by closing the issue

**Comment by HugoMendes98** [comment]
@nigelmann let it open for now in case something happens while implementing https://github.com/PDG-2023/Project/issues/34.
