### ISSUE TITLE
[Backend] Search endpoint and/or `$like` operator

### ISSUE THREAD

**Issue by HugoMendes98** [PDG-2023/Project#56]
A simple endpoint with a text parameter that looks into `location`, `item-model` and `location` entities (for an inventory).
> The necessary data to be returned is 
> - id
> - name
> - description?
> - "key" (what entity is it)

If this endpoint is not made, then a `$like` operator should be implemented instead.

**Comment by noahboegli** [comment]
I'll take that

**Comment by noahboegli** [comment]
I'd say to continue our logic we sould implement a like operator
But would it be better for you to have the search endpoint ?

**Comment by HugoMendes98** [comment]
I think that both should be implemented.

So the "complex" search has its own endpoint to look into a lot of data.
And `$like` to do a simple text reseach from the *locations* page for example.

**Comment by noahboegli** [comment]
Aight I'll see what I can do tomorrow
