### ISSUE TITLE
[Backend] `$in` operator

### ISSUE THREAD

**Issue by HugoMendes98** [PDG-2023/Project#57]
Explanation by an example:

When showing the locations, a shadow appears for the locations that have children (mock-up).
Currently, I can make a request for each location.
However, doing a single request like `locations?where[parentLocationId][$in][0]=1&where[parentLocationId][$in][1]=2` could be better.

As we are not aiming towards the performance for now, this can be ignored.
But it could help for other applications that have not yet be encountered.

**Comment by noahboegli** [comment]
Currently it is too much hassle to implement.

Do we really need it ? Is there an altenative (an OR where maybe ?)

**Comment by noahboegli** [comment]
@HugoMendes98

**Comment by HugoMendes98** [comment]
Can do with an `$or`, if you manage to do that

**Comment by noahboegli** [comment]
To be fair, given that we are Friday and the deadline is approaching like a rocketship on its way to mars, I'd vouch against implementing it and sticking to making multiple queries.
