### ISSUE TITLE
Get entities for inventory (missing filter)

### ISSUE THREAD

**Issue by HugoMendes98** [PDG-2023/Project#95]
When doing `/inventory/<id>/<entity>`, everything is always returned.

Only entities related to the inventory id should be returned

**Comment by noahboegli** [comment]
@nigelmann Any progress on this ?

**Comment by noahboegli** [comment]
@nigelmann Come on I've asked you 2 minutes ago, why do I even pay you for ?

**Comment by nigelmann** [comment]
This has been fixed in #91
